const sideData = [
  {
    type: "menuData",
    data: [
      {
        id: 1,
        menuName: "Home",
        url: "/NHAI/Dashboard",
        subMenu: [
          { id: 1, name: "Snapshot", check: true, action: [], url: "#" },
          { id: 2, name: "Financial", check: false, url: "#", action: [] },
          { id: 3, name: "Financial(D)", check: false, url: "#", action: [] },
          { id: 4, name: "Bank", check: true, url: "#", action: [] },
          { id: 5, name: "Zone", check: true, url: "#", action: [] },
          { id: 6, name: "RO", check: true, url: "#", action: [] },
          { id: 7, name: "PIU", check: true, url: "#", action: [] },
          { id: 8, name: "Account Level", check: true, url: "#", action: [] },
          { id: 9, name: "Transaction", check: true, url: "#", action: [] },
          { id: 10, name: "Ageing", check: true, url: "#", action: [] },
          { id: 11, name: "Events", check: true, url: "#", action: [] },
          { id: 12, name: "Limit Ledger", check: true, url: "#", action: [] },
          { id: 13, name: "Velocity", check: true, url: "#", action: [] },
        ],
      },
      {
        id: 2,
        menuName: "Admin",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "User",
            url: "/NHAI/Users",
            check: true,
            action: [
              { id: 1, actionName: "List", check: true },
              { id: 2, actionName: "Modify", check: true },
              { id: 3, actionName: "Add", check: true },
              { id: 4, actionName: "View", check: true },
              { id: 5, actionName: "Delete", check: true },
            ],
          },
          {
            id: 2,
            name: "User Profile",
            url: "/NHAI/Profiles",
            check: true,
            action: [
              { id: 1, actionName: "List", check: true },
              { id: 2, actionName: "Modify", check: true },
              { id: 3, actionName: "Add", check: false },
              { id: 4, actionName: "View", check: false },
              { id: 5, actionName: "Delete", check: false },
            ],
          },
          {
            id: 3,
            name: "User Group",
            url: "/NHAI/Groups",
            check: true,
            action: [
              { id: 1, actionName: "List", check: true },
              { id: 2, actionName: "Modify", check: true },
              { id: 3, actionName: "Add", check: false },
              { id: 4, actionName: "View", check: false },
              { id: 5, actionName: "Delete", check: false },
            ],
          },
          {
            id: 4,
            name: "Menu Management",
            url: "/NHAI/MenuManagement",
            check: true,
            action: [],
          },
          {
            id: 5,
            name: "Assign Rights",
            url: "/NHAI/AssignRights",
            check: false,
            action: [],
          },
          {
            id: 6,
            name: "Rule",
            url: "/NHAI/Rule",
            check: false,
            action: [],
          },
          {
            id: 7,
            name: "File Upload",
            url: "/NHAI/FileUpload",
            check: true,
            action: [],
          },
          {
            id: 8,
            name: "Mapping Master",
            url: "/NHAI/MappingMaster",
            check: true,
            action: [],
          },
          {
            id: 9,
            name: "Job Execution Log",
            url: "/NHAI/JobExecutionLog",
            check: true,
            action: [],
          },
        ],
      },
      {
        id: 3,
        menuName: "Manage Password",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "Change Password",
            url: "/NHAI/ChangePassword",
            check: true,
            action: [],
          },
        ],
      },
      {
        id: 4,
        menuName: "Reports",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "User Login Report",
            url: "/NHAI/UserLoginReport",
            check: true,
            action: [],
          },
          {
            id: 2,
            name: "User Active/Inactive",
            url: "/NHAI/UserActiveInactiveReport",
            check: true,
            action: [],
          },
          {
            id: 3,
            name: "FIFO Ageing Report",
            url: "/NHAI/FIFOAgeingReport",
            check: true,
            action: [],
          },
        ],
      },
      {
        id: 5,
        menuName: "Pending Approval",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "User Request",
            url: "/NHAI/UserRequests",
            check: true,
            action: [],
          },

          {
            id: 2,
            name: "User Profile Request",
            url: "/NHAI/profileRequests",
            check: true,
            action: [],
          },
          {
            id: 3,
            name: "User Group Request",
            url: "/NHAI/groupRequests",
            check: true,
            action: [],
          },
          {
            id: 4,
            name: `Menu Management Request`,
            url: "/NHAI/MenuManagementRequests",
            check: true,
            action: [],
          },
          {
            id: 5,
            name: "Mapping Master Request",
            url: "/NHAI/MappingMasterRequests",
            check: true,
            action: [],
          },
        ],
      },
    ],
  },
];
export default sideData;
