const sideData = [
  {
    type: "menuData",
    data: [
      {
        id: 1,
        menuName: "Home",
        url: "/NHAI/Dashboard",
        subMenu: [
          {
            id: 1,
            name: "Snapshot",
            check: true,
            oldCheck: false,
            action: [],
            url: "#",
          },
          {
            id: 2,
            name: "Financial",
            check: false,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 3,
            name: "Financial(D)",
            check: false,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 4,
            name: "Bank",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 5,
            name: "Zone",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 6,
            name: "RO",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 7,
            name: "PIU",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 8,
            name: "Account Level",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 9,
            name: "Transaction",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 10,
            name: "Ageing",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 11,
            name: "Events",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 12,
            name: "Limit Ledger",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
          {
            id: 13,
            name: "Velocity",
            check: true,
            oldCheck: false,
            url: "#",
            action: [],
          },
        ],
      },
      {
        id: 2,
        menuName: "Admin",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "User",
            url: "/NHAI/Users",
            check: true,
            action: [
              { id: 3, actionName: "Add", oldCheck: false, check: false },
              { id: 4, actionName: "View", oldCheck: false, check: true },
              { id: 2, actionName: "Update", oldCheck: false, check: true },
              { id: 5, actionName: "Delete", oldCheck: false, check: true },
            ],
          },
          {
            id: 2,
            name: "User Profile",
            url: "/NHAI/Profiles",
            check: true,
            action: [
              { id: 3, actionName: "Add", oldCheck: false, check: false },
              { id: 4, actionName: "View", oldCheck: false, check: false },
              { id: 2, actionName: "Update", oldCheck: false, check: true },
              { id: 5, actionName: "Delete", oldCheck: false, check: false },
            ],
          },
          {
            id: 3,
            name: "User Group",
            url: "/NHAI/Groups",
            check: true,
            action: [
              { id: 3, actionName: "Add", oldCheck: false, check: false },
              { id: 4, actionName: "View", oldCheck: false, check: false },
              { id: 2, actionName: "Update", oldCheck: false, check: true },
              { id: 5, actionName: "Delete", oldCheck: false, check: false },
            ],
          },
          {
            id: 4,
            name: "Menu Management",
            url: "/NHAI/MenuManagement",
            check: true,
            oldCheck: false,
            action: [],
          },
          {
            id: 7,
            name: "File Upload",
            url: "/NHAI/FileUpload",
            check: true,
            oldCheck: false,
            action: [],
          },
          {
            id: 8,
            name: "Mapping Master",
            url: "/NHAI/MappingMaster",
            check: true,
            oldCheck: false,
            action: [],
          },
          {
            id: 9,
            name: "Job Execution Log",
            url: "/NHAI/JobExecutionLog",
            check: true,
            oldCheck: false,
            action: [],
          },
        ],
      },
      {
        id: 3,
        menuName: "Manage Password",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "Change Password",
            url: "/NHAI/ChangePassword",
            check: true,
            oldCheck: false,
            action: [],
          },
        ],
      },
      {
        id: 4,
        menuName: "Reports",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "User Login Report",
            url: "/NHAI/UserLoginReport",
            check: true,
            oldCheck: false,
            action: [],
          },
          {
            id: 2,
            name: "User Active/Inactive",
            url: "/NHAI/UserActiveInactiveReport",
            check: true,
            oldCheck: false,
            action: [],
          },
          {
            id: 3,
            name: "FIFO Ageing Report",
            url: "/NHAI/FIFOAgeingReport",
            check: true,
            oldCheck: false,
            action: [],
          },
        ],
      },
      {
        id: 5,
        menuName: "Pending Approval",
        url: "#",
        subMenu: [
          {
            id: 1,
            name: "User Request",
            url: "/NHAI/UserRequests",
            oldCheck: false,
            check: true,
            action: [],
          },

          {
            id: 2,
            name: "User Profile Request",
            url: "/NHAI/profileRequests",
            oldCheck: false,
            check: true,
            action: [],
          },
          {
            id: 3,
            name: "User Group Request",
            url: "/NHAI/groupRequests",
            oldCheck: false,
            check: true,
            action: [],
          },
          {
            id: 4,
            name: `Menu Management Request`,
            url: "/NHAI/MenuManagementRequests",
            oldCheck: false,
            check: true,
            action: [],
          },
          {
            id: 5,
            name: "Mapping Master Request",
            url: "/NHAI/MappingMasterRequests",
            oldCheck: false,
            check: true,
            action: [],
          },
        ],
      },
    ],
  },
];
export default sideData;
